## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
import numpy as np
mat_1=np.arange(1,10).reshape(3,3)
mat_2=np.arange(1,10).reshape(3,3)

In [2]:
#element-wise mult
print(mat_1*mat_2)
#dot product
print(mat_1.dot(mat_2))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


## Write a NumPy program to compute the determinant of a given square array

In [3]:
mat_3=np.arange(1,10).reshape(3,3)

In [4]:
print(np.linalg.det(mat_1))

0.0


## Write a NumPy program to compute the cross product of two given vectors

In [5]:
vec_1=np.array([1,2,3])
vec_2=np.array([4,5,6])

In [6]:
print(np.cross(vec_1,vec_2))

[-3  6 -3]


## Write a NumPy program to compute the condition number of a given matrix
the condition number of a function measures how much the output value of the function can change for a small change in the input argument. This is used to measure how sensitive a function is to changes or errors in the input, and how much error in the output results from an error in the input.

*hint: look for something similar in the `linalg` module*

In [7]:
mat_4=np.arange(1,10).reshape(3,3)

In [8]:
print(np.linalg.cond(mat_4))

5.0522794445385096e+16


## Write a NumPy program to compute the inverse of a given matrix

In [9]:
mat_5=np.array=([[1,2],
                [5,9]])

In [10]:
print(np.linalg.inv(mat_5))

[[-9.  2.]
 [ 5. -1.]]
